#!/usr/bin/env bash
set -x
pics=$1
delay=${2:-0.1}

while true; do
	for p in $(cat $pics); do
		feh --bg-fill $p
		sleep $delay
	done

	sleep 2

	for p in $(tac $pics); do
		feh --bg-fill $p
		sleep $delay
	done

	sleep 2
done
