#!@zsh@
set -euo pipefail

filea=$1
fileb=$2
out=$3

if [ "$(ls -A "$out")" ]; then
	echo Directory $out not empty
	exit 1
fi

mkdir -p "$out"

resolution=$4

stepcount=${5:-30}
blurfactor=${6:-20}
blurquality=${7:-2}

filear="$(mktemp).png"
filebr="$(mktemp).png"

@magick@/bin/magick -monitor "$filea" -resize "$resolution^" \
	-gravity center -crop $resolution+0+0 +repage "$filear"
@magick@/bin/magick -monitor "$fileb" -resize "$resolution^" \
	-gravity center -crop $resolution+0+0 +repage "$filebr"

step() {
	local k=$1
	local n=$2
	@bc@/bin/bc -l <<< "
		p=a(1)*4
		x=p/$n*$k-p/2
		y=(s(x)+1)*50
		z=c(x)*$blurfactor
		print y,\" \",z,\"\n\"
	"
}
for k in $(seq -f "%02g" 1 $stepcount); do
	step $k $((stepcount + 1)) | read blend blur
	echo "Blend: $blend, blur: $blur"
	tmp="$(mktemp).png"
	@magick@/bin/composite -monitor "$filear" "$filebr" -blend $blend% "$tmp"
	@magick@/bin/magick -monitor "$tmp" -gaussian-blur $((blur * $blurquality)),$blur "$out/$k.png"
done
